### ISSUE TITLE
StackExchange.RRedis.RedisCache Error

### ISSUE THREAD

**Issue by ssvinayram** [timbarrass/redis.workflow#14]
Hi, I am getting the error StackExchange.RRedis.RedisCache as given below .What will be the reason ?please note that the below two reference are mandatory in both layers.

Compiler Error Message: CS0433: The type 'StackExchange.Redis.RedisCache' exists in both 'c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\905ba337\869e4911\assembly\dl3\012624dd\5f2a6f1c_f300d101\SPWebSite.DLL' and 'c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\905ba337\869e4911\assembly\dl3\7c5ea972\24d84f0e_f300d101\BusinessLayer.DLL'

SUggest some solutions.

**Comment by timbarrass** [comment]
Hey - I'm not an ASP guru but this feels like a common problem - does this help?http://stackoverflow.com/q/371426/389828

**Comment by timbarrass** [comment]
Closing, think this is an ASP problem, not one with this project
